services:
  backend:
    build:
      target: dev
    volumes:
      - ./backend:/backend
      - /backend/node_modules
  frontend:
    build:
      target: dev
    volumes:
      - ./frontend:/frontend
      - /frontend/node_modules

volumes:
  db_data:
    name: dev