services:
    database:
        image: postgres:15-alpine
        restart: unless-stopped
        environment:
            - POSTGRES_DB
            - POSTGRES_USER
            - POSTGRES_PASSWORD
        volumes:
            - db_data:/var/lib/postgresql/data
        ports:
            - "1234:5432"

    frontend:
        build:
            context: ./frontend
            dockerfile: Dockerfile
            target: production
        restart: unless-stopped
        ports:
           - "8080:80"

volumes:
    db_data: